service: serverless-template

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or falls back to what we have set in the provider section.
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'ap-south-1'}
  bundle:
    linting: false
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  timeout: 10
  logRetentionInDays: 90
  logs:
    httpApi: true
  httpApi:
    cors: true

functions:
  app:
    handler: functions/handler.hello
    events:
      - httpApi:
          path: "/hello"
          method: "GET"

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
