service: template-serverless

custom:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}
  bundle:
    linting: false
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  timeout: 10
  logRetentionInDays: 90
  logs:
    httpApi: true
  httpApi:
    cors:
      allowedOrigins: '*'
      allowedHeaders: '*'
      allowedMethods:
        - GET
        - OPTIONS

functions:
  app:
    handler: functions/handler.hello
    events:
      - httpApi:
          path: '/hello'
          method: 'GET'

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
